/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.itemsgui;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.Arrays;
import entity.Item;
import models.ItemTableModel;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import components.DialogWithInputs;
import components.InputWithLabel;

/**
 *
 * @author Admin
 */
public class itemsgui extends javax.swing.JFrame {
    private ArrayList<Item> itemArray = new ArrayList<Item>();

    /**
     * Creates new form itemsgui
     */
    public itemsgui() {
        initComponents();
    }

    private void initTable() {
        itemArray.add(new Item(1, "item 1", 123.12f, 10));
        itemArray.add(new Item(2, "item 2", 123.12f, 10));
        itemArray.add(new Item(3, "item 3", 123.12f, 10));
        itemArray.add(new Item(4, "item 4", 123.12f, 10));
        itemArray.add(new Item(5, "item 5", 123.12f, 10));

        itemTableModel = new ItemTableModel(itemArray);

        itemTable.setModel(itemTableModel);
        itemTable.setShowHorizontalLines(true);
        itemTable.setAutoCreateRowSorter(true);
        itemTable.getTableHeader().setReorderingAllowed(false);

        ListSelectionModel cellSelectionModel = itemTable.getSelectionModel();

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                int[] selectedRows = itemTable.getSelectedRows();

                rowActionButtonContainer.setVisible(selectedRows.length > 0);
                toolbarLabel.setText(selectedRows.length + " rows selected.");
            }

        });
    }

    private void initDialogs() {
        addItemDialog = new DialogWithInputs(this, "Add New Item", "Add New Item", inputData -> {
            var id = itemArray.size();

            itemArray.add(
                    new Item(id,
                            inputData.get("Name").get(0).getText(),
                            Float.parseFloat(inputData.get("Price").get(0).getText()),
                            Integer.parseInt(inputData.get("Quantity").get(0).getText())));

            JOptionPane.showMessageDialog(addItemDialog, "Added new item with ID: " + id, "Successfully added item",
                    JOptionPane.INFORMATION_MESSAGE);
            itemTableModel.fireTableDataChanged();
            addItemDialog.setVisible(false);
            addItemDialog.clearAll();
        });

        addItemDialog
                .addInput(new InputWithLabel("Name").setValidator("^[a-zA-Z0-9]*$",
                        "Name can only contain letters and numbers"))
                .addInput(new InputWithLabel("Price").setValidator("^-?\\d+(\\.\\d+)?$",
                        "Price has to be a number or a decimal"))
                .addInput(new InputWithLabel("Quantity").setValidator("^-?\\d+$", "Quantity has to be a whole number"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        searchInputField = new javax.swing.JTextField();
        addNewItemBtn = new javax.swing.JButton();
        rowActionsPanel = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        clearSelectionButton = new javax.swing.JButton();
        rowActionButtonContainer = new javax.swing.JPanel();
        editSelectedBtn = new javax.swing.JButton();
        deleteSelectedBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        toolbarLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        initDialogs();

        jPanel10.setPreferredSize(new java.awt.Dimension(380, 20));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Price");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel10.add(jLabel4, java.awt.BorderLayout.LINE_START);

        searchInputField.addKeyListener(new KeyListener() {
            @Override
            public void keyPressed(KeyEvent e) {
                return;
            }

            @Override
            public void keyReleased(KeyEvent e) {
                searchInputFieldChange(e);
            }

            @Override
            public void keyTyped(KeyEvent e) {
                return;
            }
        });

        jPanel10.add(textField, java.awt.BorderLayout.CENTER);

        jPanel11.setPreferredSize(new java.awt.Dimension(380, 20));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Quantity");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel11.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField3, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Item Viewer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 0));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jPanel12.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel6.setText("Search Items");
        jPanel12.add(jLabel6, java.awt.BorderLayout.LINE_START);
        jPanel12.add(searchInputField, java.awt.BorderLayout.CENTER);

        addNewItemBtn.setText("New +");
        addNewItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel12.add(addNewItemBtn, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel12);

        rowActionsPanel.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        clearSelectionButton.setText("Clear Selection");
        clearSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSelection(evt);
            }
        });
        jPanel15.add(clearSelectionButton);

        rowActionsPanel.add(jPanel15, java.awt.BorderLayout.CENTER);

        rowActionButtonContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        rowActionButtonContainer.setVisible(false);

        editSelectedBtn.setText("Edit");

        editSelectedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSelected(evt);
            }
        });

        rowActionButtonContainer.add(editSelectedBtn);

        deleteSelectedBtn.setText("Delete");

        deleteSelectedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelected(evt);
            }
        });

        rowActionButtonContainer.add(deleteSelectedBtn);

        rowActionsPanel.add(rowActionButtonContainer, java.awt.BorderLayout.LINE_END);

        jPanel4.add(rowActionsPanel);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        initTable();

        jScrollPane1.setViewportView(itemTable);

        jPanel5.add(jScrollPane1);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, "card2");

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        jPanel6.add(toolbarLabel);
        jPanel6.add(jProgressBar1);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearSelection(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        itemTable.clearSelection();
    }// GEN-LAST:event_jButton4ActionPerformed

    private void deleteSelected(java.awt.event.ActionEvent evt) {
        var selected = itemTable.getSelectedRows();
        var selectedItems = Arrays.stream(selected).mapToObj((i) -> itemTableModel.getRowItem(i)).toList();
        int selection = JOptionPane.showConfirmDialog(this, "Delete items with " + String.join(" ,", Arrays.stream(selected).mapToObj(String::valueOf).toArray(String[]::new)) + " IDs?", "Delete Selected Items",
                    JOptionPane.YES_NO_OPTION);
        
        if (selection == 0) {
            for (Item item : selectedItems) {
                itemTableModel.removeItem(item);
            }
        }

        itemTableModel.fireTableDataChanged();
    }
    
    private void editSelected(java.awt.event.ActionEvent evt) {

    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        System.out.println("Windows Opened");
    }// GEN-LAST:event_formWindowOpened

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void searchInputFieldChange(KeyEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
        var searchText = searchInputField.getText();
        
        itemTableModel.search(searchText);
    }// GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        addItemDialog.setVisible(true);
    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemsgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemsgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemsgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemsgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itemsgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DialogWithInputs addItemDialog;
    private javax.swing.JButton addNewItemBtn;
    private javax.swing.JButton editSelectedBtn;
    private javax.swing.JButton deleteSelectedBtn;
    private javax.swing.JButton clearSelectionButton;
    private javax.swing.JLabel toolbarLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable itemTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField textField;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField searchInputField;
    private javax.swing.JPanel rowActionButtonContainer;
    private javax.swing.JPanel rowActionsPanel;
    // End of variables declaration//GEN-END:variables
    private ItemTableModel itemTableModel;
}
